version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Build Project and Run Tests
          command: mvn clean install
